### PR TITLE
Update Accounts.sol

### PR DESCRIPTION
**Pull request by Aryan9592**
Same as #177 

Fixed some typo errors within the comments

### CODE REVIEW

**Comment by gnkz** [comment]
Hey @Aryan9592! Thanks for contributing to vulcan. As we discussed before https://github.com/nomoixyz/vulcan/pull/177 we are not worried about optimizations since this is a library meant to be used on a dev environment so we prefer clarity over optimizations. This time we cannot accept the optimizations changes on the loops but the fixes on typos are more than welcome!

We love contributions tho, we are really grateful and please keep them coming! 🖖

Also if you are using Vulcan in your projects we are actually looking for feedback so we would appreciate any comments you have about modules, codebase, project structure, docs, etc.

**Comment by Aryan9592** [comment]
Ohk, then I should revert back the changes except the typos fixes

**Comment by Aryan9592** [comment]
Closing #218

**Review by gnkz — APPROVED** [review]
LGTM

**Pull request merged**
